services:
  - type: web
    name: film-making-api
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONPATH
        value: /opt/render/project/src
    autoDeploy: true 