services:
  - type: web
    name: film-making
    env: python
    region: oregon
    buildCommand: ./build.sh
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/src
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
    plan: free
    branch: main
    healthCheckPath: /docs
    numInstances: 1
    pullRequestPreviewsEnabled: false 